/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Chat;

/**
 *
 * @author SarenDev
 */
public class MainGUIFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainGUIFrame
     */
    public MainGUIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chatPanel = new javax.swing.JPanel();
        statusPanel = new javax.swing.JPanel();
        statusMessage = new javax.swing.JLabel();
        statusIndicator = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        scrollView = new javax.swing.JScrollPane();
        chatView = new javax.swing.JTextArea();
        chatInputSelector = new javax.swing.JTabbedPane();
        broadcastTab = new javax.swing.JPanel();
        broadcastMessage = new javax.swing.JTextField();
        broadcastSend = new javax.swing.JButton();
        groupMessageTab = new javax.swing.JPanel();
        groupMessage = new javax.swing.JTextField();
        groupSend = new javax.swing.JButton();
        groupSelector = new javax.swing.JComboBox<>();
        directMessageTab = new javax.swing.JPanel();
        directMessage = new javax.swing.JTextField();
        directUpload = new javax.swing.JButton();
        directSend = new javax.swing.JButton();
        userSelector = new javax.swing.JComboBox<>();
        encryptCheckbox = new javax.swing.JCheckBox();
        topBar = new javax.swing.JMenuBar();
        clientMenu = new javax.swing.JMenu();
        connectMenuItem = new javax.swing.JMenuItem();
        disconnectMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        Server = new javax.swing.JMenu();
        listUsersMenuItem = new javax.swing.JMenuItem();
        joinGroup = new javax.swing.JMenuItem();
        createGroup = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        statusPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        statusMessage.setText("Disconnected");

        statusIndicator.setBackground(new java.awt.Color(85, 85, 85));
        statusIndicator.setLayout(null);

        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        usernameLabel.setText("Logged out");

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(statusIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usernameLabel))
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(statusIndicator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(statusMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        scrollView.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollView.setAutoscrolls(true);

        chatView.setEditable(false);
        chatView.setColumns(20);
        chatView.setLineWrap(true);
        chatView.setRows(5);
        chatView.setFocusable(false);
        scrollView.setViewportView(chatView);

        broadcastSend.setText("Send");
        broadcastSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                broadcastSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout broadcastTabLayout = new javax.swing.GroupLayout(broadcastTab);
        broadcastTab.setLayout(broadcastTabLayout);
        broadcastTabLayout.setHorizontalGroup(
            broadcastTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(broadcastTabLayout.createSequentialGroup()
                .addComponent(broadcastMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(broadcastSend, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        broadcastTabLayout.setVerticalGroup(
            broadcastTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(broadcastTabLayout.createSequentialGroup()
                .addGroup(broadcastTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(broadcastMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(broadcastSend, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        chatInputSelector.addTab("Server", broadcastTab);

        groupSend.setText("Send");
        groupSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupSendActionPerformed(evt);
            }
        });

        groupSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select a group --", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout groupMessageTabLayout = new javax.swing.GroupLayout(groupMessageTab);
        groupMessageTab.setLayout(groupMessageTabLayout);
        groupMessageTabLayout.setHorizontalGroup(
            groupMessageTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, groupMessageTabLayout.createSequentialGroup()
                .addGroup(groupMessageTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(groupSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groupMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(groupSend, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        groupMessageTabLayout.setVerticalGroup(
            groupMessageTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupMessageTabLayout.createSequentialGroup()
                .addGroup(groupMessageTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(groupSend, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(groupMessage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(groupSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chatInputSelector.addTab("Group", groupMessageTab);

        directUpload.setText("Upload");

        directSend.setText("Send");
        directSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directSendActionPerformed(evt);
            }
        });

        userSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select a user --", "Item 2", "Item 3", "Item 4" }));

        encryptCheckbox.setText("Encrypt");
        encryptCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout directMessageTabLayout = new javax.swing.GroupLayout(directMessageTab);
        directMessageTab.setLayout(directMessageTabLayout);
        directMessageTabLayout.setHorizontalGroup(
            directMessageTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, directMessageTabLayout.createSequentialGroup()
                .addGroup(directMessageTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(directMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(directMessageTabLayout.createSequentialGroup()
                        .addComponent(userSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(encryptCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(directMessageTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(directUpload)
                    .addComponent(directSend, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        directMessageTabLayout.setVerticalGroup(
            directMessageTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(directMessageTabLayout.createSequentialGroup()
                .addGroup(directMessageTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(directSend, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(directMessage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(directMessageTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(directUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encryptCheckbox))
                .addContainerGap())
        );

        chatInputSelector.addTab("DM", directMessageTab);

        javax.swing.GroupLayout chatPanelLayout = new javax.swing.GroupLayout(chatPanel);
        chatPanel.setLayout(chatPanelLayout);
        chatPanelLayout.setHorizontalGroup(
            chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollView)
            .addGroup(chatPanelLayout.createSequentialGroup()
                .addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
            .addComponent(chatInputSelector, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        chatPanelLayout.setVerticalGroup(
            chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatPanelLayout.createSequentialGroup()
                .addComponent(scrollView, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(chatInputSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        getContentPane().add(chatPanel, java.awt.BorderLayout.PAGE_END);

        clientMenu.setText("Mocca");

        connectMenuItem.setText("Connect...");
        connectMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectMenuItemActionPerformed(evt);
            }
        });
        clientMenu.add(connectMenuItem);

        disconnectMenuItem.setText("Disconnect");
        disconnectMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectMenuItemActionPerformed(evt);
            }
        });
        clientMenu.add(disconnectMenuItem);

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        clientMenu.add(aboutMenuItem);

        topBar.add(clientMenu);

        Server.setText("Server");

        listUsersMenuItem.setText("ListConnectedUsers");
        listUsersMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listUsersMenuItemActionPerformed(evt);
            }
        });
        Server.add(listUsersMenuItem);

        joinGroup.setText("Join Group");
        Server.add(joinGroup);

        createGroup.setText("Create Group");
        Server.add(createGroup);

        topBar.add(Server);

        setJMenuBar(topBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void broadcastSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_broadcastSendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_broadcastSendActionPerformed

    private void connectMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_connectMenuItemActionPerformed

    private void disconnectMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disconnectMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void listUsersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listUsersMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listUsersMenuItemActionPerformed

    private void directSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directSendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_directSendActionPerformed

    private void groupSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupSendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_groupSendActionPerformed

    private void encryptCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encryptCheckboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Server;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JTextField broadcastMessage;
    private javax.swing.JButton broadcastSend;
    private javax.swing.JPanel broadcastTab;
    private javax.swing.JTabbedPane chatInputSelector;
    private javax.swing.JPanel chatPanel;
    private javax.swing.JTextArea chatView;
    private javax.swing.JMenu clientMenu;
    private javax.swing.JMenuItem connectMenuItem;
    private javax.swing.JMenuItem createGroup;
    private javax.swing.JTextField directMessage;
    private javax.swing.JPanel directMessageTab;
    private javax.swing.JButton directSend;
    private javax.swing.JButton directUpload;
    private javax.swing.JMenuItem disconnectMenuItem;
    private javax.swing.JCheckBox encryptCheckbox;
    private javax.swing.JTextField groupMessage;
    private javax.swing.JPanel groupMessageTab;
    private javax.swing.JComboBox<String> groupSelector;
    private javax.swing.JButton groupSend;
    private javax.swing.JMenuItem joinGroup;
    private javax.swing.JMenuItem listUsersMenuItem;
    private javax.swing.JScrollPane scrollView;
    private javax.swing.JPanel statusIndicator;
    private javax.swing.JLabel statusMessage;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JMenuBar topBar;
    private javax.swing.JComboBox<String> userSelector;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
